export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOCALE_SELECTED = 'LOCALE_SELECTED';
export const TRANSLATIONS = 'TRANSLATIONS';

export const LOGIN_FORM_DATA = 'LOGIN_FORM_DATA';

export const CAMPSITE_CREATE_USER_MODAL = 'CAMPSITE_CREATE_USER_MODAL';
export const CAMPSITE_LIST = 'CAMPSITE_LIST';
export const CAMPSITE_FEATURES_LIST = 'CAMPSITE_FEATURES_LIST';
export const CAMPSITE_LIST_ADD = 'CAMPSITE_LIST_ADD';
export const CAMPSITE_CREATE_ACCOUNT_MODAL = 'CAMPSITE_CREATE_ACCOUNT_MODAL';
export const CAMPSITE_OBJECT_TYPES = 'CAMPSITE_OBJECT_TYPES';

export const STATUS_LIST = 'STATUS_LIST';


export const BOOKING_CRUD_MODAL = 'BOOKING_CRUD_MODAL';

